---
- name: Snipe-IT demo playbook
  hosts: localhost
  tasks:
    - name: Include category tasks
      include_tasks: snipeit_categories.yml
    - name: Include model tasks
      include_tasks: snipeit_models.yml
  vars:
    # Local development key - shipped with the DB dump included in the repo.
    # For a production environment, this should come from a secret and not be version controlled.
    # load from a file with lookup('file', 'path/to/file')
    api_key: "{{ lookup('file', '../../dev-api-key.txt') }}"
    snipe_url: http://localhost:8080/